### PR TITLE
Wilm tap patch 1

### PR DESCRIPTION
**Pull request by wilmTap**
Addresses #72

### CODE REVIEW

**Comment by garemoko** [comment]
@wilmTap "extensions" in xAPI has a specific technical meaning should the URI instead be something like http://xapi.jisc.ac.uk/activityTypes/courseArea ?

**Comment by wilmTap** [comment]
It's a good point, but most of the URIs we've minted could/will be used in both object and context. Maybe it'd be better to not include any of the object syntax in the path. i.e. http://xapi.jisc.ac.uk/courseArea?

**Comment by arc12** [comment]
I think I'd prefer vocab URIs which do not include expected usage paths. Wilbert's latest URI example is fine by me, although including "xapi" does hint at a transgression the idea of this being a semantic vocabulary which is usable other than for xapi. OTOH, that is getting ahead of ourselves, so I'm happy to be a transgressor... ;-)

**Comment by wilmTap** [comment]
I did consider protocol neutrality in the web3id scheme I made for issue #73, but I think we're too far down setting up resolvability of http://xapi.jisc.ac.uk/ to change it now.

**Comment by garemoko** [comment]
Wouldn't that cause problems if/when we go down the route of hosting metadata at the uri? If it's both an activity type and an extension property, what would you put in the metadata?

**Pull request merged**
